name: Kwiki-Widgets-Links
version: 0.01
abstract: A widget that display several given links
author: Kang-min Liu <gugod@gugod.org>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
requires:
  Kwiki: 0.38
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
